# Use postgres/example user/password credentials
version: '3.4'

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: book_db

  test-db:
    image: postgis/postgis
    restart: always
    ports:
      - '5433:5432'
    expose:
      - '5432'
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: book_test_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
volumes:
  mysql-db-data:
